### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by stuartskelton** [1Mill/TI4-race-randomizer#27]
Seems the new feature has broken live. 

Here is a link to test with:
https://www.tiraces.com/shared/#NobwRAlgJmBcYAUA2BDAngUwE4AICMYANGAHYoC2GcYAQgPYBGRYWKAxhgM5zBgDCqEjjoAzHAGUUKLMwDiACzqcALp2Fi+WDAFdO3YgFUSEAG7ZOEZRC7qcAKTpIAtADlpOAFRgAugF9C4NDUyOjYOABMzGSU1DgAgkgQHMysHNywvABiGFDYKFZ0QqISjp7MACqWKCRqxQZIOADUzG4oAF5OAEp0ANbyKPFIidUcTT6+3kA

Regards

**Comment by 1Mill** [comment]
@stuartskelton, I agree that this link is not working but I cannot seem to recreate the issue with a new link. Are you still experiencing this issue when you generate a new link?

**Comment by stuartskelton** [comment]
if you are not worried about back compatibility its not a problem.  But I had a game set up this weekend, and had to download and back out of the changes so I could find get our races.
